name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (graphviz)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install package + dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (ruff)
        run: ruff check --fix src tests

      # - name: Lint (ruff)
      #   run: ruff check src tests
      - name: Format (black)
        run: black src tests
      - name: Format check (black)
        run: black --check src tests

      - name: Run tests
        run: pytest -q
