name: Deploy Docs (GitHub Pages)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (graphviz)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install project
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .

      - name: Generate workflow site
        run: |
          # Run generator via module to avoid PATH issues
          python -m digdaggraph.cli

          # Add a root redirect for Pages home
          echo "<!doctype html><meta charset='utf-8'><meta http-equiv='refresh' content='0; url=scheduled_workflows.html'><title>Redirect</title>" > index.html

          # Sanity check we actually produced the artifacts
          test -f scheduled_workflows.html
          test -d graphs

      - name: Stage artifacts for Pages
        run: |
          mkdir -p _site
          cp -v scheduled_workflows.html _site/
          cp -v index.html _site/
          cp -rv graphs _site/
          echo "Contents to deploy:" && find _site -maxdepth 2 -type f -print

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
